version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - "9092:9092"
    networks:
      - kafka-network

  producer:
    build: ./producer
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI: "mongodb+srv://dbGDR:dbYahiaUsers@cluster-gdr.yogka.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-GDR"
      MONGO_DB: mongodbVSCodePlaygroundDB
      MONGO_COLLECTION: sales
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge